import type { Product, Category, Address, Order, MasterCatalogItem, DarkStoreHub, UserProfile, StoreSettings, PromoBanner } from './types';

export const CATEGORIES: Category[] = [
  {
    id: 'all',
    name: 'All Items',
    icon: '🛒',
    badge: 'Popular',
    bgGradient: 'from-amber-50 to-orange-100',
    itemCount: 24,
  },
  {
    id: 'vegetables',
    name: 'Vegetables & Fruits',
    icon: '🥦',
    badge: 'Fresh Daily',
    bgGradient: 'from-emerald-50 to-green-100',
    itemCount: 8,
  },
  {
    id: 'dairy',
    name: 'Dairy, Bread & Eggs',
    icon: '🥛',
    badge: 'Morning Fresh',
    bgGradient: 'from-sky-50 to-blue-100',
    itemCount: 6,
  },
  {
    id: 'munchies',
    name: 'Munchies & Chips',
    icon: '🍟',
    badge: 'Up to 30% Off',
    bgGradient: 'from-yellow-50 to-amber-100',
    itemCount: 5,
  },
  {
    id: 'packaged_foods',
    name: 'Packaged Foods',
    icon: '🍜',
    badge: 'Quick Bites',
    bgGradient: 'from-rose-50 to-red-100',
    itemCount: 4,
  },
  {
    id: 'cold_drinks',
    name: 'Cold Drinks & Juices',
    icon: '🥤',
    badge: 'Chilled',
    bgGradient: 'from-cyan-50 to-teal-100',
    itemCount: 4,
  },
  {
    id: 'sweet_tooth',
    name: 'Chocolates & Sweets',
    icon: '🍫',
    badge: 'Sweet Deals',
    bgGradient: 'from-purple-50 to-pink-100',
    itemCount: 3,
  },
  {
    id: 'staples',
    name: 'Atta, Rice & Dal',
    icon: '🌾',
    badge: 'Super Saver',
    bgGradient: 'from-stone-50 to-amber-100',
    itemCount: 4,
  }
];

export const PRODUCTS: Product[] = [
  // Vegetables & Fruits
  {
    id: 'prod-1',
    name: 'Fresh Farm Hass Avocados',
    brand: 'Fresho Organics',
    unit: '2 pcs (approx. 400g)',
    price: 139,
    mrp: 180,
    discountPercent: 23,
    image: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=600&auto=format&fit=crop&q=80',
    category: 'vegetables',
    subcategory: 'Exotic Produce',
    description: 'Creamy Hass avocados with rich buttery texture, ripened naturally.',
    deliveryTime: '8 MINS',
    rating: 4.8,
    ratingCount: 342,
    inStock: true,
    barcode: '8901030829101',
    tags: ['trending', 'deal_of_day', 'bestseller']
  },
  {
    id: 'prod-2',
    name: 'Organic Red Vine Tomatoes',
    brand: 'Nature Choice',
    unit: '500 g',
    price: 32,
    mrp: 45,
    discountPercent: 29,
    image: 'https://images.unsplash.com/photo-1546094096-0df4bcaaa337?w=600&auto=format&fit=crop&q=80',
    category: 'vegetables',
    subcategory: 'Fresh Veggies',
    description: 'Crisp, firm, and tangy red tomatoes sourced directly from verified local farms.',
    deliveryTime: '8 MINS',
    rating: 4.6,
    ratingCount: 890,
    inStock: true,
    barcode: '8901030829102',
    tags: ['trending', 'recently_purchased']
  },
  {
    id: 'prod-3',
    name: 'Crispy Baby Spinach (Hydroponic)',
    brand: 'Urban Greens',
    unit: '200 g pack',
    price: 49,
    mrp: 65,
    discountPercent: 25,
    image: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=600&auto=format&fit=crop&q=80',
    category: 'vegetables',
    subcategory: 'Leafy Greens',
    description: 'Washed and ready to cook hydroponic baby spinach tender leaves.',
    deliveryTime: '8 MINS',
    rating: 4.7,
    ratingCount: 420,
    inStock: true,
    barcode: '8901030829103',
    tags: ['trending']
  },
  {
    id: 'prod-4',
    name: 'Sweet Ruby Strawberries Box',
    brand: 'Mahabaleshwar Pure',
    unit: '1 Box (200g)',
    price: 99,
    mrp: 140,
    discountPercent: 29,
    image: 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=600&auto=format&fit=crop&q=80',
    category: 'vegetables',
    subcategory: 'Fresh Fruits',
    description: 'Hand-picked ruby strawberries, deliciously sweet with refreshing aroma.',
    deliveryTime: '8 MINS',
    rating: 4.9,
    ratingCount: 650,
    inStock: true,
    barcode: '8901030829104',
    tags: ['deal_of_day', 'bestseller']
  },
  {
    id: 'prod-5',
    name: 'Shimla Crisp Royal Gala Apples',
    brand: 'Himalayan Orchard',
    unit: '4 pcs (approx. 550g)',
    price: 119,
    mrp: 160,
    discountPercent: 26,
    image: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=600&auto=format&fit=crop&q=80',
    category: 'vegetables',
    subcategory: 'Fresh Fruits',
    description: 'Juicy, sweet, and crisp apples packed with natural antioxidants and fiber.',
    deliveryTime: '8 MINS',
    rating: 4.7,
    ratingCount: 512,
    inStock: true,
    barcode: '8901030829105',
    tags: ['recently_purchased']
  },

  // Dairy, Bread & Eggs
  {
    id: 'prod-6',
    name: 'Pasteurized Homogenized Toned Milk',
    brand: 'Amul Taaza',
    unit: '1 Litre Pouch',
    price: 54,
    mrp: 54,
    discountPercent: 0,
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=600&auto=format&fit=crop&q=80',
    category: 'dairy',
    subcategory: 'Milk & Cream',
    description: 'Pure, wholesome toned milk rich in calcium and vitamin A & D.',
    deliveryTime: '8 MINS',
    rating: 4.9,
    ratingCount: 2410,
    inStock: true,
    barcode: '8901262010053',
    tags: ['trending', 'recently_purchased', 'bestseller']
  },
  {
    id: 'prod-7',
    name: 'Fresh Farm White Eggs (Brown Box)',
    brand: 'Eggoz Country Fresh',
    unit: 'Pack of 6',
    price: 58,
    mrp: 75,
    discountPercent: 23,
    image: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=600&auto=format&fit=crop&q=80',
    category: 'dairy',
    subcategory: 'Eggs',
    description: 'UV sanitized antibiotic-free farm fresh eggs rich in natural protein.',
    deliveryTime: '8 MINS',
    rating: 4.8,
    ratingCount: 1890,
    inStock: true,
    barcode: '8901262010054',
    tags: ['trending', 'deal_of_day', 'recently_purchased']
  },
  {
    id: 'prod-8',
    name: 'Artisan 100% Whole Wheat Brown Bread',
    brand: 'The Health Baker',
    unit: '400 g Loaf',
    price: 45,
    mrp: 50,
    discountPercent: 10,
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop&q=80',
    category: 'dairy',
    subcategory: 'Bakery & Bread',
    description: 'No added maida, fiber-rich artisan soft bread baked every sunrise.',
    deliveryTime: '8 MINS',
    rating: 4.6,
    ratingCount: 780,
    inStock: true,
    barcode: '8901262010055',
    tags: ['recently_purchased']
  },
  {
    id: 'prod-9',
    name: 'Salted Butter Yellow Brick',
    brand: 'Amul Butter',
    unit: '100 g',
    price: 58,
    mrp: 60,
    discountPercent: 3,
    image: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=600&auto=format&fit=crop&q=80',
    category: 'dairy',
    subcategory: 'Butter & Spreads',
    description: 'The classic Utterly Butterly Delicious salted butter adored across generations.',
    deliveryTime: '8 MINS',
    rating: 4.9,
    ratingCount: 3100,
    inStock: true,
    barcode: '8901262010056',
    tags: ['trending', 'bestseller']
  },
  {
    id: 'prod-10',
    name: 'Soft Malai Fresh Paneer Block',
    brand: 'MilkyMist Elite',
    unit: '200 g',
    price: 89,
    mrp: 110,
    discountPercent: 19,
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=600&auto=format&fit=crop&q=80',
    category: 'dairy',
    subcategory: 'Paneer & Cheese',
    description: 'Soft cottage cheese made from 100% cow milk, perfect for curries and tikkas.',
    deliveryTime: '8 MINS',
    rating: 4.7,
    ratingCount: 940,
    inStock: true,
    barcode: '8901262010057',
    tags: ['deal_of_day']
  },

  // Munchies & Chips
  {
    id: 'prod-11',
    name: 'Magic Masala Crinkle Potato Chips',
    brand: "Lay's India",
    unit: '90 g Party Pack',
    price: 35,
    mrp: 40,
    discountPercent: 13,
    image: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=600&auto=format&fit=crop&q=80',
    category: 'munchies',
    subcategory: 'Potato Chips',
    description: 'Crispy sliced golden potatoes dusted with spicy blend of Indian spices.',
    deliveryTime: '8 MINS',
    rating: 4.8,
    ratingCount: 1540,
    inStock: true,
    barcode: '8901491100234',
    tags: ['trending', 'deal_of_day', 'bestseller']
  },
  {
    id: 'prod-12',
    name: 'Spicy Tangy Kurkure Masala Munch',
    brand: 'Kurkure Munch',
    unit: '75 g',
    price: 20,
    mrp: 20,
    discountPercent: 0,
    image: 'https://images.unsplash.com/photo-1621996346565-e3d5d6281691?w=600&auto=format&fit=crop&q=80',
    category: 'munchies',
    subcategory: 'Corn Puffs & Snacks',
    description: 'Crunchy tedhe-medhe corn curls loaded with authentic spicy chatpata flavour.',
    deliveryTime: '8 MINS',
    rating: 4.6,
    ratingCount: 1120,
    inStock: true,
    barcode: '8901491100235',
    tags: ['trending']
  },
  {
    id: 'prod-13',
    name: 'Jalapeño & Cheddar Gourmet Nachos',
    brand: 'Cornitos Sizzlin',
    unit: '150 g with Salsa Dip',
    price: 85,
    mrp: 110,
    discountPercent: 23,
    image: 'https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?w=600&auto=format&fit=crop&q=80',
    category: 'munchies',
    subcategory: 'Nachos & Dips',
    description: 'Crisp corn tortilla chips with spicy Mexican jalapeño and smooth cheddar.',
    deliveryTime: '8 MINS',
    rating: 4.7,
    ratingCount: 560,
    inStock: true,
    barcode: '8901491100236',
    tags: ['deal_of_day']
  },
  {
    id: 'prod-14',
    name: 'Roasted California Almonds (Salted)',
    brand: 'Nutty Gritties',
    unit: '200 g Zip Pouch',
    price: 229,
    mrp: 299,
    discountPercent: 23,
    image: 'https://images.unsplash.com/photo-1508061253366-f7da158b6d46?w=600&auto=format&fit=crop&q=80',
    category: 'munchies',
    subcategory: 'Dry Fruits & Nuts',
    description: 'Slow roasted jumbo almonds lightly dusted with Himalayan pink salt.',
    deliveryTime: '8 MINS',
    rating: 4.9,
    ratingCount: 420,
    inStock: true,
    barcode: '8901491100237',
    tags: ['trending']
  },

  // Packaged Foods
  {
    id: 'prod-15',
    name: '2-Minute Special Masala Instant Noodles',
    brand: 'Maggi Nestle',
    unit: 'Pack of 4 (280g)',
    price: 52,
    mrp: 60,
    discountPercent: 13,
    image: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?w=600&auto=format&fit=crop&q=80',
    category: 'packaged_foods',
    subcategory: 'Instant Noodles',
    description: 'The unforgettable taste of favorite 2-minute noodles made with quality spices.',
    deliveryTime: '8 MINS',
    rating: 4.9,
    ratingCount: 4500,
    inStock: true,
    barcode: '8901058852381',
    tags: ['trending', 'recently_purchased', 'bestseller']
  },
  {
    id: 'prod-16',
    name: 'Creamy Tomato & Basil Pasta Sauce',
    brand: 'Barilla Vero Gusto',
    unit: '350 g Glass Jar',
    price: 189,
    mrp: 240,
    discountPercent: 21,
    image: 'https://images.unsplash.com/photo-1621996346565-e3d5d6281691?w=600&auto=format&fit=crop&q=80',
    category: 'packaged_foods',
    subcategory: 'Pastas & Sauces',
    description: 'Slow-simmered Italian sun-ripened tomatoes infused with extra virgin olive oil.',
    deliveryTime: '8 MINS',
    rating: 4.6,
    ratingCount: 310,
    inStock: true,
    barcode: '8901058852382',
    tags: ['deal_of_day']
  },
  {
    id: 'prod-17',
    name: 'Instant Oats with Real Veggies',
    brand: 'Quaker Superbowl',
    unit: '400 g Pouch',
    price: 89,
    mrp: 115,
    discountPercent: 23,
    image: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=600&auto=format&fit=crop&q=80',
    category: 'packaged_foods',
    subcategory: 'Breakfast Cereals',
    description: '100% whole grain rolled oats with carrots, green peas, and savory masala seasoning.',
    deliveryTime: '8 MINS',
    rating: 4.5,
    ratingCount: 680,
    inStock: true,
    barcode: '8901058852383',
    tags: ['recently_purchased']
  },

  // Cold Drinks & Juices
  {
    id: 'prod-18',
    name: 'Original Taste Carbonated Soda Can',
    brand: 'Coca-Cola',
    unit: '300 ml Chill Can',
    price: 38,
    mrp: 40,
    discountPercent: 5,
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=600&auto=format&fit=crop&q=80',
    category: 'cold_drinks',
    subcategory: 'Soft Drinks',
    description: 'Crisp, refreshing, and bubbly cola served chilled right to your door in 8 minutes.',
    deliveryTime: '8 MINS',
    rating: 4.8,
    ratingCount: 1980,
    inStock: true,
    barcode: '8901764012111',
    tags: ['trending', 'deal_of_day']
  },
  {
    id: 'prod-19',
    name: '100% Cold-Pressed Alphonso Mango Juice',
    brand: 'Raw Pressery',
    unit: '250 ml Bottle',
    price: 80,
    mrp: 99,
    discountPercent: 19,
    image: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?w=600&auto=format&fit=crop&q=80',
    category: 'cold_drinks',
    subcategory: 'Fresh Juices',
    description: 'Pure Ratnagiri Alphonso mango pulp cold pressed with no added refined sugars.',
    deliveryTime: '8 MINS',
    rating: 4.8,
    ratingCount: 820,
    inStock: true,
    barcode: '8901764012112',
    tags: ['trending', 'bestseller']
  },
  {
    id: 'prod-20',
    name: 'Electrolyte Sparkling Lemon Water',
    brand: 'Bisleri Vedica Fizz',
    unit: '500 ml Pet Bottle',
    price: 35,
    mrp: 40,
    discountPercent: 13,
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&auto=format&fit=crop&q=80',
    category: 'cold_drinks',
    subcategory: 'Sparkling & Flavoured',
    description: 'Himalayan mountain spring water infused with sparkling natural zesty lemon essence.',
    deliveryTime: '8 MINS',
    rating: 4.7,
    ratingCount: 390,
    inStock: true,
    barcode: '8901764012113',
    tags: ['recently_purchased']
  },

  // Atta, Rice & Staples
  {
    id: 'prod-21',
    name: 'Sharbati 100% MP Chakki Fresh Atta',
    brand: 'Aashirvaad Select',
    unit: '5 kg Bag',
    price: 289,
    mrp: 340,
    discountPercent: 15,
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&auto=format&fit=crop&q=80',
    category: 'staples',
    subcategory: 'Atta & Flours',
    description: 'Made from grains which are heavy on the palm and golden amber in color for fluffy rotis.',
    deliveryTime: '8 MINS',
    rating: 4.9,
    ratingCount: 3120,
    inStock: true,
    barcode: '8901030894561',
    tags: ['deal_of_day', 'bestseller']
  },
  {
    id: 'prod-22',
    name: 'Aged Royal Basmati Long Grain Rice',
    brand: 'India Gate Feast',
    unit: '1 kg Pouch',
    price: 145,
    mrp: 185,
    discountPercent: 22,
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&auto=format&fit=crop&q=80',
    category: 'staples',
    subcategory: 'Rice & Grains',
    description: 'Pristine 2-year naturally aged basmati grains offering tantalizing royal aroma.',
    deliveryTime: '8 MINS',
    rating: 4.8,
    ratingCount: 1640,
    inStock: true,
    barcode: '8901030894562',
    tags: ['trending']
  },
  {
    id: 'prod-23',
    name: 'Unpolished Organic Toor Dal (Arhar)',
    brand: 'Tata Sampann Pulses',
    unit: '1 kg Pack',
    price: 165,
    mrp: 195,
    discountPercent: 15,
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80',
    category: 'staples',
    subcategory: 'Dals & Pulses',
    description: 'Unpolished split pigeon peas untouched by water polishing, preserving natural nutrients.',
    deliveryTime: '8 MINS',
    rating: 4.7,
    ratingCount: 1210,
    inStock: true,
    barcode: '8901030894563',
    tags: ['recently_purchased']
  },

  // Chocolates & Sweets
  {
    id: 'prod-24',
    name: 'Silk Hazelnut Cream Chocolate Bar',
    brand: 'Cadbury Dairy Milk',
    unit: '143 g Bar',
    price: 175,
    mrp: 195,
    discountPercent: 10,
    image: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=600&auto=format&fit=crop&q=80',
    category: 'sweet_tooth',
    subcategory: 'Chocolates',
    description: 'Smooth, silky milk chocolate embedded with whole roasted crunchy Turkish hazelnuts.',
    deliveryTime: '8 MINS',
    rating: 4.9,
    ratingCount: 2280,
    inStock: true,
    barcode: '8901233029118',
    tags: ['trending', 'deal_of_day', 'bestseller']
  }
];

export const DARK_STORE_HUBS: DarkStoreHub[] = [
  {
    id: 'hub-01',
    name: 'Bellandur Central Hub',
    code: 'BLR-HUB-04',
    coordinates: { lat: 12.9280, lng: 77.6740 },
    baseEtaMinutes: 8,
    status: 'active',
    ridersActive: 14,
  },
  {
    id: 'hub-02',
    name: 'Indiranagar Express Pod',
    code: 'BLR-HUB-12',
    coordinates: { lat: 12.9784, lng: 77.6408 },
    baseEtaMinutes: 7,
    status: 'active',
    ridersActive: 18,
  },
  {
    id: 'hub-03',
    name: 'Koramangala HyperMart Hub',
    code: 'BLR-HUB-08',
    coordinates: { lat: 12.9352, lng: 77.6245 },
    baseEtaMinutes: 9,
    status: 'active',
    ridersActive: 12,
  },
  {
    id: 'hub-04',
    name: 'Whitefield Tech Corridor Hub',
    code: 'BLR-HUB-19',
    coordinates: { lat: 12.9698, lng: 77.7499 },
    baseEtaMinutes: 11,
    status: 'active',
    ridersActive: 9,
  },
];

export const INITIAL_ADDRESSES: Address[] = [
  {
    id: 'addr-1',
    title: 'Home',
    addressLine: 'Flat 402, Tower B, Green Glen Heights, Bellandur',
    landmark: 'Opposite Central Park',
    tag: 'home',
    isDefault: true,
    latitude: 12.9260,
    longitude: 77.6762,
    coordinates: { lat: 12.9260, lng: 77.6762 },
    distanceKm: 0.9,
    etaMinutes: 8,
    darkStoreName: 'Dark Store #04 (Bellandur Central Hub)',
    houseNumber: 'Flat 402, Tower B',
    floorBuilding: 'Green Glen Heights'
  },
  {
    id: 'addr-2',
    title: 'Office',
    addressLine: 'Desk 14-A, 4th Floor, Tech Hub Arena, Outer Ring Road',
    landmark: 'Near EcoWorld Gate 3',
    tag: 'work',
    isDefault: false,
    latitude: 12.9220,
    longitude: 77.6840,
    coordinates: { lat: 12.9220, lng: 77.6840 },
    distanceKm: 1.4,
    etaMinutes: 10,
    darkStoreName: 'Dark Store #04 (Bellandur Central Hub)',
    houseNumber: 'Desk 14-A, 4th Floor',
    floorBuilding: 'Tech Hub Arena'
  },
  {
    id: 'addr-3',
    title: "Parents' Place",
    addressLine: 'House #42, 7th Cross, 3rd Main, Indiranagar',
    landmark: 'Behind Corner House',
    tag: 'other',
    isDefault: false,
    latitude: 12.9750,
    longitude: 77.6410,
    coordinates: { lat: 12.9750, lng: 77.6410 },
    distanceKm: 0.6,
    etaMinutes: 7,
    darkStoreName: 'Dark Store #12 (Indiranagar Express Pod)',
    houseNumber: 'House #42',
    floorBuilding: '7th Cross, 3rd Main'
  }
];

export const PAST_ORDERS: Order[] = [
  {
    id: 'ord-1051',
    orderNumber: 'J1S-95002',
    date: 'Today, 08:02 PM',
    status: 'out_for_delivery',
    total: 485,
    deliveryEta: 'Within 25 mins',
    paymentMethod: 'UPI (PhonePe)',
    address: INITIAL_ADDRESSES[0],
    assignedRiderId: 'usr-rider-1',
    assignedRiderName: 'Rahul Verma',
    items: [
      { product: PRODUCTS[0], quantity: 1 }, // Aashirvaad Atta
      { product: PRODUCTS[5], quantity: 2 }, // Amul Milk
      { product: PRODUCTS[8], quantity: 1 }  // Paneer
    ]
  },
  {
    id: 'ord-1050',
    orderNumber: 'J1S-94988',
    date: 'Today, 07:40 PM',
    status: 'packing',
    total: 260,
    deliveryEta: 'Within 35 mins',
    paymentMethod: 'Cash on Delivery',
    address: INITIAL_ADDRESSES[1],
    assignedRiderId: 'usr-rider-1',
    assignedRiderName: 'Rahul Verma',
    items: [
      { product: PRODUCTS[2], quantity: 1 }, // Baby Spinach
      { product: PRODUCTS[10], quantity: 2 }, // Lays Chips
      { product: PRODUCTS[14], quantity: 1 }  // Dairy Milk
    ]
  },
  {
    id: 'ord-1049',
    orderNumber: 'J1S-94821',
    date: 'Today, 06:45 PM',
    status: 'out_for_delivery',
    total: 312,
    deliveryEta: 'Within 18 mins',
    paymentMethod: 'UPI (Google Pay)',
    address: INITIAL_ADDRESSES[2],
    assignedRiderId: 'usr-rider-2',
    assignedRiderName: 'Vikram Singh',
    items: [
      { product: PRODUCTS[5], quantity: 2 }, // Milk
      { product: PRODUCTS[7], quantity: 1 }, // Bread
      { product: PRODUCTS[6], quantity: 1 }  // Eggs
    ]
  },
  {
    id: 'ord-1048',
    orderNumber: 'J1S-93810',
    date: 'Yesterday, 09:12 PM',
    status: 'delivered',
    total: 219,
    deliveryEta: 'Delivered in 9 mins',
    paymentMethod: 'Credit Card',
    address: INITIAL_ADDRESSES[0],
    assignedRiderId: 'usr-rider-1',
    assignedRiderName: 'Rahul Verma',
    items: [
      { product: PRODUCTS[10], quantity: 2 }, // Lays
      { product: PRODUCTS[17], quantity: 2 }  // Coke
    ]
  }
];

export const SEARCH_SUGGESTIONS = [
  'milk',
  'fresh bread',
  'eggs',
  'amul butter',
  'avocado',
  'lays magic masala',
  'coca cola',
  'maggi noodles',
  'aashirvaad atta',
  'silk chocolate',
  'tomatoes'
];

export const MASTER_CATALOG_SAMPLES: MasterCatalogItem[] = [
  {
    id: 'mc-001',
    barcode: '8901030829101',
    brand_name: 'Fresho Organics',
    product_title: 'Fresh Farm Hass Avocados',
    weight_metric: '2 pcs (approx. 400g)',
    category: 'Vegetables & Fruits',
    subcategory: 'Exotic Produce',
    image_url: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=600&auto=format&fit=crop&q=80',
    purchase_price: 110,
    selling_price: 139,
    mrp: 175,
    profit_margin_amount: 29,
    profit_margin_percent: 20.86,
    is_active: true,
    status: 'active',
    source_provider: 'Local Market Mandi API v2',
    created_at: '2026-09-12 06:00:00',
    updated_at: '2026-09-12 06:30:00'
  },
  {
    id: 'mc-002',
    barcode: '8901491100555',
    brand_name: 'Haldirams Classic',
    product_title: 'Aloo Bhujia Namkeen Crunchy',
    weight_metric: '400 g',
    category: 'Munchies & Chips',
    subcategory: 'Namkeen & Savouries',
    image_url: 'https://images.unsplash.com/photo-1599490659213-e2b9527bd087?w=600&auto=format&fit=crop&q=80',
    purchase_price: null, // Crucial rule: NULL by default until Admin sets it
    selling_price: null,  // Crucial rule: NULL / 0 keeps item hidden from customer catalog
    mrp: 120,
    profit_margin_amount: null,
    profit_margin_percent: null,
    is_active: false,
    status: 'pending_admin_pricing',
    source_provider: 'Wholesale Cloud Scraper Cron',
    created_at: '2026-09-12 06:45:10',
    updated_at: '2026-09-12 06:45:10'
  },
  {
    id: 'mc-003',
    barcode: '8901058859999',
    brand_name: 'Nescafe Gold',
    product_title: 'Blend Arabica Instant Coffee Glass Jar',
    weight_metric: '100 g',
    category: 'Tea, Coffee & Health Drinks',
    subcategory: 'Coffee',
    image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop&q=80',
    purchase_price: null, // Flagged NULL
    selling_price: 0,    // Flagged 0
    mrp: 450,
    profit_margin_amount: null,
    profit_margin_percent: null,
    is_active: false,
    status: 'pending_admin_pricing',
    source_provider: 'FMCG Master Barcode Registry',
    created_at: '2026-09-12 06:50:22',
    updated_at: '2026-09-12 06:50:22'
  },
  {
    id: 'mc-004',
    barcode: '8901262010099',
    brand_name: 'Mother Dairy',
    product_title: 'Cow Milk Fresh Pouch (Chilled)',
    weight_metric: '500 ml',
    category: 'Dairy, Bread & Eggs',
    subcategory: 'Milk',
    image_url: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=600&auto=format&fit=crop&q=80',
    purchase_price: 27,
    selling_price: 33,
    mrp: 35,
    profit_margin_amount: 6,
    profit_margin_percent: 18.18,
    is_active: true,
    status: 'active',
    source_provider: 'Daily Dairy Mandi Feed',
    created_at: '2026-09-12 06:55:00',
    updated_at: '2026-09-12 07:10:00'
  },
  {
    id: 'mc-005',
    barcode: '8902001928312',
    brand_name: 'Britannia',
    product_title: 'Good Day Butter Cookies Family Pack',
    weight_metric: '300 g',
    category: 'Bakery & Biscuits',
    subcategory: 'Cookies',
    image_url: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=600&auto=format&fit=crop&q=80',
    purchase_price: 0, // Zero price flagged
    selling_price: 0, // Zero price flagged
    mrp: 60,
    profit_margin_amount: 0,
    profit_margin_percent: 0,
    is_active: false,
    status: 'pending_admin_pricing',
    source_provider: 'Wholesale Cloud Scraper Cron',
    created_at: '2026-09-12 07:05:14',
    updated_at: '2026-09-12 07:05:14'
  },
  {
    id: 'mc-006',
    barcode: '8901030384910',
    brand_name: 'Tata Sampann',
    product_title: 'Unpolished Toor Dal Protein Rich',
    weight_metric: '1 kg',
    category: 'Atta, Rice & Dals',
    subcategory: 'Pulses',
    image_url: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&auto=format&fit=crop&q=80',
    purchase_price: 135,
    selling_price: 172,
    mrp: 195,
    profit_margin_amount: 37,
    profit_margin_percent: 21.51,
    is_active: true,
    status: 'active',
    source_provider: 'Grain Wholesale Mandi Feed',
    created_at: '2026-09-12 07:15:30',
    updated_at: '2026-09-12 07:20:00'
  }
];

export const INITIAL_STORE_SETTINGS: StoreSettings = {
  storeName: 'Just1Shop Flagship Dark Store Hub',
  address: 'Building 4B, Outer Ring Road, Bellandur, Bengaluru, Karnataka 560103',
  latitude: 12.935242,
  longitude: 77.624462,
  serviceRadiusKm: 15,
  maxDeliveryHours: 24,
  isDeliveryActive: true,
  ownerPhone: '8987767301',
};

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'usr-owner',
    name: 'Store Administrator',
    phone: '8987767301',
    email: 'admin@just1shop.com',
    role: 'owner',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    createdAt: '2026-01-01',
    isActive: true,
  },
  {
    id: 'usr-admin-1',
    name: 'Amit Sharma',
    phone: '9876543210',
    email: 'admin.ops@just1shop.com',
    role: 'admin',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    createdAt: '2026-02-15',
    isActive: true,
  },
  {
    id: 'usr-rider-1',
    name: 'Rahul Verma (Express Rider)',
    phone: '9811223344',
    email: 'rahul.rider@just1shop.com',
    role: 'delivery',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    createdAt: '2026-03-10',
    isActive: true,
    assignedOrdersCount: 2,
  },
  {
    id: 'usr-rider-2',
    name: 'Vikram Singh (Fleet Partner)',
    phone: '9822334455',
    email: 'vikram.delivery@just1shop.com',
    role: 'delivery',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&auto=format&fit=crop&q=80',
    createdAt: '2026-04-01',
    isActive: true,
    assignedOrdersCount: 1,
  },
  {
    id: 'usr-cust-1',
    name: 'Priya Sharma',
    phone: '9844556677',
    email: 'priya.customer@gmail.com',
    role: 'user',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&auto=format&fit=crop&q=80',
    createdAt: '2026-05-12',
    isActive: true,
  }
];

export const INITIAL_PROMO_BANNERS: PromoBanner[] = [
  {
    id: 'banner-durga-puja',
    title: 'Durga Puja Maha Utsav Sale',
    subtitle: 'Special 50% discount on Sweets, Dry Fruits, Fresh Ghee & Puja Essentials',
    badge: '🌸 DURGA PUJA SPECIAL',
    discountText: 'FLAT 50% OFF',
    couponCode: 'PUJA50',
    ctaText: 'Shop Festive Deals',
    bannerType: 'festive',
    theme: 'durga_puja',
    gradient: 'from-red-900 via-rose-800 to-amber-900',
    emojiIcon: '🪔',
    isActive: true,
    priority: 1,
    validUntil: 'Live for Festive Season'
  },
  {
    id: 'banner-company-exclusive',
    title: 'Company Exclusive Member Sale',
    subtitle: 'VIP member access: Premium imported fruits, cold-pressed oils & gourmet dairy',
    badge: '👑 COMPANY EXCLUSIVE',
    discountText: 'EXTRA 35% SAVINGS',
    couponCode: 'EXCLUSIVE35',
    ctaText: 'Claim Member Offers',
    bannerType: 'exclusive',
    theme: 'exclusive',
    gradient: 'from-purple-950 via-indigo-900 to-slate-900',
    emojiIcon: '💎',
    isActive: true,
    priority: 2,
    validUntil: 'Just1Shop VIP Access'
  },
  {
    id: 'banner-winner-sale',
    title: 'Grand Winner Super Saver',
    subtitle: 'Mega price crash on pantry essentials, beverages, munchies & kitchen staples',
    badge: '🏆 WINNER SALE',
    discountText: 'UP TO 60% OFF',
    couponCode: 'WINNER100',
    ctaText: 'Grab Winner Deals',
    bannerType: 'sale',
    theme: 'winner_sale',
    gradient: 'from-amber-600 via-orange-600 to-red-700',
    emojiIcon: '⚡',
    isActive: true,
    priority: 3,
    validUntil: 'Limited Stock Rush'
  }
];
